---
title: "My english activity log"
---

24/09/2019 : I read some articles for my presentation.

25/09/2019 :I read some articles for my presentation.

27/09/2019 :I read some articles for my presentation and I searched for some Youtube channels about science (especially Biology). I found : iBiology, Biomentors Classes Online, Beverly Biology, Vincent Racaniello, Alex Lee, Sea&amp;me - Marine Biology stuff with Maria.

29/09/2019 : I found other Youtube channels : Bleier Biology, Biology Bugbears, Bozeman science, Amoeba sisters, Free science lessons, Biomedical and Biological sciences.
I read the first chapter of "The Hobbit".

02/10/2019 : I read the wikipedia article about cockatiel for my Data Science homework.

05/10/2019 : I read some articles for my presentation and I watched a video about diffusion (https://www.youtube.com/watch?v=jhszFBtBPoI).

06/10/2019 : I read some articles for my presentation, I read the second chapter of "The Hobbit" and I watched a vide about cell cycle (https://www.youtube.com/watch?v=QVCjdNxJreE).

09/10/2019 : I read an article for my presentation.

10/10/2019 : I watched a video about the respiratory system (https://www.youtube.com/watch?v=2guHOnEt0e8).

11/10/2019 : I worked on my first article for my portfolio.

12/10/2019 : I read some articles for my presentation.

13/10/2019 : I worked on my presentation and I read the third chapter of "The Hobbit".

14/10/2019 : I read some articles for my presentation.

15/10/2019 : I read some articles for my presentation and I watched a documentary about coral bleaching https://www.youtube.com/watch?v=5cr8S5tTiz4.

16/10/2019 : I read some articles for my presentation.

17/10/2019 : I watched a video about the types of natural selection https://www.youtube.com/watch?v=DBPGLythma0.

19/10/2019 : I watched a video about marine biology https://www.youtube.com/watch?v=uWZXC3mjeZU.

20/10/2019 : I watched a video about resting potential but it was said the opposite of what we were taught in class (so I don't put the link).




