---
title: "My English activity log"

author:
  - name: Aurélie Pinchart
date: 12-15-2019
preview: english.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 2019

## September

* **24/09/2019** : I read some articles for my presentation.

* **25/09/2019** :I read some articles for my presentation.

* **27/09/2019** :I read some articles for my presentation and I searched for some Youtube channels about science (especially Biology). I found : iBiology, Biomentors Classes Online, Beverly Biology, Vincent Racaniello, Alex Lee, Sea&amp;me - Marine Biology stuff with Maria.

* **29/09/2019** : I found other Youtube channels : Bleier Biology, Biology Bugbears, Bozeman science, Amoeba sisters, Free science lessons, Biomedical and Biological sciences.
I read the first chapter of "The Hobbit".

## October

* **02/10/2019** : I read the wikipedia article about cockatiel for my Data Science homework.

* **05/10/2019** : I read some articles for my presentation and I watched a video about diffusion (https://www.youtube.com/watch?v=jhszFBtBPoI).

* **06/10/2019** : I read some articles for my presentation, I read the second chapter of "The Hobbit" and I watched a vide about cell cycle (https://www.youtube.com/watch?v=QVCjdNxJreE).

* **09/10/2019** : I read an article for my presentation.

* **10/10/2019** : I watched a video about the respiratory system (https://www.youtube.com/watch?v=2guHOnEt0e8).

* **11/10/2019** : I worked on my first article for my portfolio.

* **12/10/2019** : I read some articles for my presentation.

* **13/10/2019** : I worked on my presentation and I read the third chapter of "The Hobbit".

* **14/10/2019** : I read some articles for my presentation.

* **15/10/2019** : I read some articles for my presentation and I watched a documentary about coral bleaching https://www.youtube.com/watch?v=5cr8S5tTiz4.

* **16/10/2019** : I read some articles for my presentation.

* **17/10/2019** : I watched a video about the types of natural selection https://www.youtube.com/watch?v=DBPGLythma0.

* **19/10/2019** : I watched a video about marine biology https://www.youtube.com/watch?v=uWZXC3mjeZU. I also read the fouth chapter of "The Hobbit".

* **20/10/2019** : I watched a video about resting potential but it was said the opposite of what we were taught in class (so I don't put the link).

* **22/10/2019** : I watched a video about predation https://www.youtube.com/watch?v=6jXwEOit5vM.

* **24/10/2019** : I watched a video about genetic drift https://www.youtube.com/watch?v=W0TM4LQmoZY and a video about natural selection https://www.youtube.com/watch?v=7VM9YxmULuo.

* **26/10/2019** : I watched a video about the loss of biodiversity https://www.youtube.com/watch?v=vCkDxD0DV0Q and I read the fifth chapter of "T he Hobbit".

* **27/10/2019** : I watched a video about the protein structure and folding https://www.youtube.com/watch?v=hok2hyED9go.

* **29/10/2019** : I watched a video about mutations https://www.youtube.com/watch?v=vl6Vlf2thvI.

## November

* **01/11/2019** : I watched a video about microscope drawings https://www.youtube.com/watch?v=NLKZ95aHqE4.

* **02/11/2019** : I watched a video about ethology https://www.youtube.com/watch?v=BvLihzeQzGk.

* **03/11/2019** : I watched a video about stress management https://www.youtube.com/watch?v=2vhIGYKW4gY and I read the sixth chapter of "The Hobbit".

* **05/11/2019** : I watched a video about ethology (the second part) https://www.youtube.com/watch?v=jEZIUVU0BCU.

* **07/11/2019** : I watched  the last part of the video about ethology https://www.youtube.com/watch?v=bspxe_-ilC4.

* **09/11/2019** : I watched a video about enzymes https://www.youtube.com/watch?v=6Acx6b3Hzsk 

* **10/11/2019** : I watched a video about germination https://www.youtube.com/watch?v=cmzhvl5kOc0 and I read the seventh chapter of "The Hobbit".

* **13/11/2019** : I watched a video about CRISPR https://www.youtube.com/watch?v=MnYppmstxIs.

* **15/11/2019** : I watched a video about ATP https://www.youtube.com/watch?v=23ZzI6WZS28.

* **16/11/2019** : I watched a video about bacteria https://www.youtube.com/watch?v=ORB866QSGv8.

* **17/11/2019** : I watched a video about autotrophs and heterotrophs https://www.youtube.com/watch?v=f8G7IulYxiA and I read the eighth of "The Hobbit".

* **20/11/2019** : I watched a video about DNA and RNA https://www.youtube.com/watch?v=JQByjprj_mA.

* **21/11/2019** : I watched a video about skin https://www.youtube.com/watch?v=b9Fim9kKVLs.

* **23/11/2019** : I watched a video about reflex arc https://www.youtube.com/watch?v=SMcF01utk3Y.

* **24/11/2019** : I watched a video about signal transduction pathways https://www.youtube.com/watch?v=236d5LDUFSs and I read the ninth chapter of "The Hobbit".

* **25/11/2019** : I watched a video about electrochemical gradient https://www.youtube.com/watch?v=Ba02v7eoVWQ.

* **27/11/2019** : I watched a video about viruses https://www.youtube.com/watch?v=8FqlTslU22s.

* **29/11/2019** : I watched a video about organic molecules https://www.youtube.com/watch?v=tcmGGGJx9zI.

## December

* **01/12/2019** : I read the tenth chapter of "The Hobbit".

* **03/12/2019** : I watched a video about microscopes https://www.youtube.com/watch?v=tVcEEw6qbBQ.

* **05/12/2019** : I watched a video about reproductive adaptations https://www.youtube.com/watch?v=b_w4Nexv-0s.

* **07/12/2019** : I watched a video about DNA replication https://www.youtube.com/watch?v=Qqe4thU-os8.

* **08/12/2019** : I watched a video about imprinting https://www.youtube.com/watch?v=vwaiVxxpi7E and I read the eleventh chapter of "The Hobbit".

* **10/12/2019** : I watched a video about protists and fungi https://www.youtube.com/watch?v=zK7Ckmxxqds.

* **13/12/2019** : I went to the scientific workshop training and listened to the presentation of my friends.

* **14/12/2019** : I watched a video about the heart https://www.youtube.com/watch?v=XpeeiqjRGB4.

* **15/12/2019** : I watched a video about blood vessels https://www.youtube.com/watch?v=G2bJimNUjSI and i read the twelfth chapter of "The Hobbit".

* **17/12/2019** : I watched a video about study skills and habits https://www.youtube.com/watch?v=jCdTaLI5tVk.

* **19/12/2019**  :I watched a video about Archaea https://www.youtube.com/watch?v=VGcT1-XaWgk.

* **22/12/2019** : I read the 13th chapter of "The Hobbit".

* **29/12/2019** : I read the 14th chapter of "The Hobbit".


# 2020

## January

* **05/01/2020** : I read the 15th chapter of "The Hobbit".

* **26/01/2020** : I read the 16th chapter of "The Hobbit".

* **28/01/2020** : I read the 17th chapter of "The Hobbit".

* **31/01/2020** : I read the 18th chapter of "The Hobbit".

## February

* **02/02/2020** : I read the last chapter of "The Hobbit".
